/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;

import java.awt.Color;
import java.awt.Font;
import konektor.Koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Kelompok 8 Best Peformance (Rata Kanan,Ora Turu)
 * 
 */


public class homeStaff extends javax.swing.JFrame {
    
    private DefaultTableModel DftTblModel_barang;
    private String SQL;
    
    static String a,b,c;


    /**
     * Creates new form homeAdmin
     */
    public homeStaff() {
        initComponents();
        this.TampilData();
//        this.tabelmobil();
//        this.tabelDataPengembalian();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.tampilCombo();
        this.tampilCombo2();
//        this.tampilCombo3();
        
        ActionListener acl=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                a=berjalan.getText();
                b=a.substring(0,1);
                c=a.substring(1, a.length());
                berjalan.setText(c+b);
                
            }
        }; new javax.swing.Timer(300,acl).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHomeAdmin = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        LABELJALAN = new javax.swing.JLabel();
        berjalan = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputJaminan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        inputNomor = new javax.swing.JTextField();
        btnBersih = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        namapeminjam = new javax.swing.JLabel();
        nomortlp = new javax.swing.JLabel();
        jaminan = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        inputPlat = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        merkMobil = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        typeMobil = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tahunMobil = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        hargaSewa = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        kondisi = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        lamaSewa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        totalHarga = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSewaMobil = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        namaPeminjam = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        hargaSewaHari = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tglSewa = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tglPengembalian = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pilihNopol = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        lamaDipinjam = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMobilDipinjam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(25, 118, 211));
        jTabbedPane1.setForeground(new java.awt.Color(25, 118, 211));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 118, 211));
        jButton1.setText("KELUAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(625, 589, 323, 40);

        LABELJALAN.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        LABELJALAN.setForeground(new java.awt.Color(255, 255, 255));
        LABELJALAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABELJALAN.setText("Selamat Datang...");
        jPanel1.add(LABELJALAN);
        LABELJALAN.setBounds(580, 220, 420, 41);

        berjalan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        berjalan.setForeground(new java.awt.Color(255, 255, 255));
        berjalan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        berjalan.setText("Anda Sedang Berada Di Halaman Staff di CaRent Enterprise");
        jPanel1.add(berjalan);
        berjalan.setBounds(480, 320, 620, 50);

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\staff.png")); // NOI18N
        jPanel1.add(jLabel39);
        jLabel39.setBounds(660, 386, 250, 190);

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("________________________________________________________");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(610, 269, 465, 39);

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel8.setBackground(new java.awt.Color(25, 118, 211));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Penyewa    :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jaminan                :");

        inputJaminan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KTP", "KK", "Sertifikat Properti" }));
        inputJaminan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJaminanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Alamat Lengkap  :");

        inputAlamat.setColumns(20);
        inputAlamat.setRows(5);
        jScrollPane2.setViewportView(inputAlamat);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("No. Tlp/WA          :");

        btnBersih.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBersih.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\bersih.png")); // NOI18N
        btnBersih.setText("Bersihkan");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnProses.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnProses.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\proses.png")); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(25, 118, 211));
        jLabel38.setText("INPUT DATA PENYEWA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel38)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnBersih)
                        .addGap(52, 52, 52)
                        .addComponent(btnProses))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputJaminan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputNomor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBersih)
                    .addComponent(btnProses))
                .addGap(56, 56, 56))
        );

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        jPanel11.setBackground(new java.awt.Color(25, 118, 211));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nama Penyewa       : ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No. Tlp/WA             :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Jaminan                   :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Alamat Lengkap     :");

        namapeminjam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namapeminjam.setForeground(new java.awt.Color(255, 255, 255));
        namapeminjam.setText("....");

        nomortlp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomortlp.setForeground(new java.awt.Color(255, 255, 255));
        nomortlp.setText("....");

        jaminan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jaminan.setForeground(new java.awt.Color(255, 255, 255));
        jaminan.setText("....");

        alamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("....");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomortlp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namapeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(namapeminjam))
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomortlp)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jaminan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(25, 118, 211));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("No. Polisi         :");

        inputPlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPlatActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Merk Mobil      :");

        merkMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        merkMobil.setForeground(new java.awt.Color(255, 255, 255));
        merkMobil.setText("....");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Type                 :");

        typeMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        typeMobil.setForeground(new java.awt.Color(255, 255, 255));
        typeMobil.setText("....");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CC                      :");

        cc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cc.setForeground(new java.awt.Color(255, 255, 255));
        cc.setText("....");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tahun                :");

        tahunMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tahunMobil.setForeground(new java.awt.Color(255, 255, 255));
        tahunMobil.setText("....");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Harga /hari       :");

        hargaSewa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hargaSewa.setForeground(new java.awt.Color(255, 255, 255));
        hargaSewa.setText("....");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Kondisi              :");

        kondisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kondisi.setForeground(new java.awt.Color(255, 255, 255));
        kondisi.setText("....");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(merkMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahunMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(hargaSewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(inputPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(typeMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(merkMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tahunMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(hargaSewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kondisi)
                    .addComponent(jLabel25))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Tgl Penyewaan        :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tgl Pengembalian   :");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Lama Penyewaan    :");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Hari");

        btnTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTotal.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\total.png")); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Rp. ");

        totalHarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalHarga.setText("....");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\sewa.png")); // NOI18N
        jButton2.setText("Sewa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(lamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(btnTotal)
                                        .addComponent(jButton2))))
                            .addComponent(jLabel18))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHarga)
                            .addComponent(jLabel28))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jScrollPane3.setBackground(new java.awt.Color(25, 118, 211));

        tblSewaMobil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblSewaMobil.setForeground(new java.awt.Color(25, 118, 211));
        tblSewaMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSewaMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSewaMobilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSewaMobil);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1499, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sewa Mobil", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jPanel14.setBackground(new java.awt.Color(25, 118, 211));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Nama Penyewa       :");

        namaPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        namaPeminjam.setText("....");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("No. Polisi                 :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Harga /hari             :");

        hargaSewaHari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hargaSewaHari.setForeground(new java.awt.Color(255, 255, 255));
        hargaSewaHari.setText("....");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Tgl Penyewaan       :");

        tglSewa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tglSewa.setForeground(new java.awt.Color(255, 255, 255));
        tglSewa.setText("....");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Tgl Pengembalian  :");

        tglPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tglPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        tglPengembalian.setText("....");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JO\\Documents\\NetBeansProjects\\kelompok projekakhir\\src\\icon\\kembalikan.png")); // NOI18N
        jButton3.setText("Proses Kembalikan Mobil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pilihNopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihNopolActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Lama Dipinjam       :");

        lamaDipinjam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lamaDipinjam.setForeground(new java.awt.Color(255, 255, 255));
        lamaDipinjam.setText("....");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Hari");

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(25, 118, 211));
        jLabel35.setText("PROSES PENGEMBALIAN SEWA ");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(hargaSewaHari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(pilihNopol, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(namaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(57, 57, 57)
                                .addComponent(tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(lamaDipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(namaPeminjam))
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihNopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(31, 31, 31)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(hargaSewaHari))
                .addGap(29, 29, 29)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tglSewa))
                .addGap(27, 27, 27)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tglPengembalian))
                .addGap(29, 29, 29)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lamaDipinjam)
                    .addComponent(jLabel36))
                .addGap(89, 89, 89)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(25, 118, 211));

        tblMobilDipinjam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMobilDipinjam.setForeground(new java.awt.Color(25, 118, 211));
        tblMobilDipinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMobilDipinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMobilDipinjamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMobilDipinjam);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pengembalian Mobil", jPanel4);

        javax.swing.GroupLayout panelHomeAdminLayout = new javax.swing.GroupLayout(panelHomeAdmin);
        panelHomeAdmin.setLayout(panelHomeAdminLayout);
        panelHomeAdminLayout.setHorizontalGroup(
            panelHomeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        panelHomeAdminLayout.setVerticalGroup(
            panelHomeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHomeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHomeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//    public void tabelDataPengembalian() {
//        DftTblModel_barang = new DefaultTableModel();
//        DftTblModel_barang.addColumn("Nama");
//        DftTblModel_barang.addColumn("No. Polisi");
//        DftTblModel_barang.addColumn("Harga");
//        DftTblModel_barang.addColumn("Tanggal Sewa");
//        DftTblModel_barang.addColumn("Tanggal Harus Dikembalikan");
//        DftTblModel_barang.addColumn("Lama Sewa");
//        DftTblModel_barang.addColumn("Total Harga");
//        DftTblModel_barang.addColumn("Telat");
//        
//
//        tblMobilDipinjam.setModel(DftTblModel_barang);
//        Connection conn = Koneksi.getConnection();
//        try {
//            java.sql.Statement stmt = conn.createStatement();
//            SQL = "select * from data_pengembalian";
//            java.sql.ResultSet res = stmt.executeQuery(SQL);
//            while (res.next()) {
//                DftTblModel_barang.addRow(new Object[]{
//                    res.getString("nama"),
//                    res.getString("nopol"),
//                    res.getString("harga"),
//                    res.getString("tgl_pinjaman"),
//                    res.getString("tgl_pengembalian"),
//                    res.getString("lama"),
//                    res.getString("total"),
//                    res.getString("telat")
//                });
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }
    
//    public void tabelmobil() {
//        DftTblModel_barang = new DefaultTableModel();
//        DftTblModel_barang.addColumn("Merek");
//        DftTblModel_barang.addColumn("CC");
//        DftTblModel_barang.addColumn("Type");
//        DftTblModel_barang.addColumn("Tahun");
//        DftTblModel_barang.addColumn("Nopol");
//        DftTblModel_barang.addColumn("Harga");
//        DftTblModel_barang.addColumn("Kondisi");
//
//        tblDataMobil.setModel(DftTblModel_barang);
//        Connection conn = Koneksi.getConnection();
//        try {
//            java.sql.Statement stmt = conn.createStatement();
//            SQL = "select * from mobil";
//            java.sql.ResultSet res = stmt.executeQuery(SQL);
//            while (res.next()) {
//                DftTblModel_barang.addRow(new Object[]{
//                    res.getString("merek"),
//                    res.getString("CC"),
//                    res.getString("tipe"),
//                    res.getString("tahun"),
//                    res.getString("nopol"),
//                    res.getString("harga"),
//                    res.getString("kondisi")
//                });
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }
    
    public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("Nama Peminjam");
        DftTblModel_barang.addColumn("No. Telp/WA");
        DftTblModel_barang.addColumn("Jaminan");
        DftTblModel_barang.addColumn("Alamat");
        DftTblModel_barang.addColumn("No Polisi");
        DftTblModel_barang.addColumn("Harga");
        DftTblModel_barang.addColumn("Tanggal Pinjam");
        DftTblModel_barang.addColumn("Tanggal Pengembalian");
        DftTblModel_barang.addColumn("Lama Peminjaman");
        DftTblModel_barang.addColumn("Total");
        tblSewaMobil.setModel(DftTblModel_barang);
        tblMobilDipinjam.setModel(DftTblModel_barang);
        
        tblSewaMobil.setModel(DftTblModel_barang);
        tblSewaMobil.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblSewaMobil.getTableHeader().setForeground(Color.BLUE);
        tblSewaMobil.getTableHeader().setBackground(Color.white);
        TableCellRenderer rendererFromHeader = tblSewaMobil.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        
        tblMobilDipinjam.setModel(DftTblModel_barang);
        tblMobilDipinjam.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblMobilDipinjam.getTableHeader().setForeground(Color.BLUE);
        tblMobilDipinjam.getTableHeader().setBackground(Color.white);
        TableCellRenderer rendererFromHeader1 = tblMobilDipinjam.getTableHeader().getDefaultRenderer();
        JLabel headerLabel1 = (JLabel) rendererFromHeader1;
        headerLabel1.setHorizontalAlignment(JLabel.CENTER);
        
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from transaksi";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("nama"),
                    res.getString("no_tlp"),
                    res.getString("jaminan"),
                    res.getString("alamat"),
                    res.getString("nopol"),
                    res.getString("harga"),
                    res.getString("tgl_pinjaman"),
                    res.getString("tgl_pengembalian"),
                    res.getString("lama"),
                    res.getString("total")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
//    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            int row = tblMobilDipinjam.getSelectedRow();
            java.sql.Statement stmt = conn.createStatement();
            SQL = "update mobil set kondisi= 'Tersedia' WHERE nopol='" + pilihNopol.getSelectedItem() + "'";
            stmt.executeUpdate(SQL);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        inputPlat();
        hapus_transaksi();
//        tabelDataPengembalian();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void clearTransaksi(){
        namaPeminjam.setText("");
        pilihNopol.setSelectedItem(0);
        hargaSewaHari.setText("");
        tglSewa.setText("");
        tglPengembalian.setText("");
        lamaDipinjam.setText("");
   }
    
    public void hapus_transaksi() {
        
        if (JOptionPane.showConfirmDialog(this, "Yakin Mengembalikan Mobil ?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            Connection conn = Koneksi.getConnection();
            try {
                int row = tblMobilDipinjam.getSelectedRow();
                java.sql.Statement stmt = conn.createStatement();
                String st = (String) pilihNopol.getSelectedItem();
                SQL = "DELETE FROM transaksi WHERE `transaksi`.`nopol` = '"+st+"'";
                
                PreparedStatement stm = conn.prepareStatement("insert into data_pengembalian(nama,no_tlp,jaminan,alamat,nopol,harga,tgl_pinjaman,tgl_pengembalian,lama,total,telat) values(?,?,?,?,?,?,?,?,?,?,?)");
                stm.setString(1, (String) tblMobilDipinjam.getValueAt(row, 0));
                stm.setString(2, (String) tblMobilDipinjam.getValueAt(row, 1));
                stm.setString(3, (String) tblMobilDipinjam.getValueAt(row, 2));
                stm.setString(4, (String) tblMobilDipinjam.getValueAt(row, 3));
                stm.setString(5, (String) tblMobilDipinjam.getValueAt(row, 4));
                stm.setString(6, (String) tblMobilDipinjam.getValueAt(row, 5));
                stm.setString(7, (String) tblMobilDipinjam.getValueAt(row, 6));
                stm.setString(8, (String) tblMobilDipinjam.getValueAt(row, 7));
                stm.setString(9, (String) tblMobilDipinjam.getValueAt(row, 8));
                stm.setString(10, (String) tblMobilDipinjam.getValueAt(row, 9));
                                
                String inputTelat = JOptionPane.showInputDialog("Masukan telat berapa hari? Jika tidak telat inputkan 0");
                int InputTelat = Integer.parseInt(inputTelat);
                int denda = 50000*InputTelat;
                String Hasil = String.valueOf(InputTelat);
                stm.setString(11, Hasil);
                
                if (InputTelat==0){
                    stm.setString(10, (String) tblMobilDipinjam.getValueAt(row, 9));
                    stm.executeUpdate();
                    stmt.executeUpdate(SQL);
                    TampilData();
//                    tabelDataPengembalian();
                    clearTransaksi();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Kamu Telat Mengembalikan Mobil Selama : " + Hasil + "Hari, Anda mendapatkan Denda sebanyak Rp. " + denda);
                    String total = (String) tblMobilDipinjam.getValueAt(row, 9);
                    int Total = Integer.parseInt(total);
                    
                    int all = Total+denda;
                    
                    String Keseluruhan = String.valueOf(all);
                    stm.setString(10, Keseluruhan);
                    
                    JOptionPane.showMessageDialog(this, "Jadi Total yang harus Anda Bayarkan adalah Rp.  " + Keseluruhan);
                    
                    stm.executeUpdate();
                    stmt.executeUpdate(SQL);
                    TampilData();
//                    tabelDataPengembalian();
                    clearTransaksi();
                }
            }catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }

    }
    
    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        inputNama.setText("");
        inputNomor.setText("");
        inputJaminan.setSelectedItem(0);
        inputAlamat.setText("");
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        if (inputNama.getText().isEmpty() || 
                inputNomor.getText().isEmpty() || 
                inputAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
        } else {
            inputNama.getText();
            inputNomor.getText();
            inputJaminan.getSelectedItem();
            inputAlamat.getText();
            
            String Nama, nomor, Jaminan, Alamat;
            Nama = String.valueOf(inputNama.getText());
            nomor = String.valueOf(inputNomor.getText());
            Jaminan = String.valueOf(inputJaminan.getSelectedItem());
            Alamat = String.valueOf(inputAlamat.getText());
            
            namapeminjam.setText(Nama);
            nomortlp.setText(nomor);
            alamat.setText(Alamat);
            jaminan.setText(Jaminan);
            
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        if (inputNama.getText().isEmpty() || 
                inputNomor.getText().isEmpty() || 
                inputAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
        }
        else {
            hitungselisih();
        }
    }//GEN-LAST:event_btnTotalActionPerformed

    public void inputPlat(){
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            String st = (String) inputPlat.getSelectedItem();
            SQL = "SELECT * FROM mobil WHERE `mobil`.`nopol` = '"+st+"'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {

                this.typeMobil.setText(res.getString("tipe"));
                this.merkMobil.setText(res.getString("merek"));
                this.cc.setText(res.getString("CC"));
                this.tahunMobil.setText(res.getString("tahun"));
                this.hargaSewa.setText(res.getString("harga"));
                this.kondisi.setText(res.getString("kondisi"));
            
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void inputPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPlatActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            String st = (String) inputPlat.getSelectedItem();
            SQL = "SELECT * FROM mobil WHERE `mobil`.`nopol` = '"+st+"'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {

                this.typeMobil.setText(res.getString("tipe"));
                this.merkMobil.setText(res.getString("merek"));
                this.cc.setText(res.getString("CC"));
                this.tahunMobil.setText(res.getString("tahun"));
                this.hargaSewa.setText(res.getString("harga"));
                this.kondisi.setText(res.getString("kondisi"));

            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_inputPlatActionPerformed

    private void inputJaminanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJaminanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJaminanActionPerformed

    public void peminjam() {
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into peminjam(nama, jaminan, alamat, telp) values(?,?,?,?)");
            stmt.setString(1, namapeminjam.getText());
            stmt.setString(2, jaminan.getText());
            stmt.setString(3, alamat.getText());
            stmt.setString(4, nomortlp.getText());
            stmt.executeUpdate();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void hapusTransaksi() {
        namapeminjam.setText("");
        jaminan.setText("");
        nomortlp.setText("");
        alamat.setText("");
        lamaSewa.setText("");
        totalHarga.setText("");

    }
    
    public void simpan() {
        if (tglPinjam.getDate().toString().isEmpty() ||
                tglKembali.getDate().toString().isEmpty() || 
                lamaSewa.getText().isEmpty() || 
                totalHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
        } else {
            try {
                Connection conn = Koneksi.getConnection();
                PreparedStatement stmt = conn.prepareStatement("insert into transaksi(nama,no_tlp,jaminan,alamat,nopol,harga,tgl_pinjaman, tgl_pengembalian, lama, total) values(?,?,?,?,?,?,?,?,?,?)");
                stmt.setString(1, namapeminjam.getText());
                stmt.setString(2, nomortlp.getText());
                stmt.setString(3, jaminan.getText());
                stmt.setString(4, alamat.getText());
                stmt.setString(5, inputPlat.getSelectedItem().toString());
                stmt.setString(6, hargaSewa.getText());
                stmt.setString(7, tglPinjam.getDate().toString());
                stmt.setString(8, tglKembali.getDate().toString());
                stmt.setString(9, lamaSewa.getText());
                stmt.setString(10, totalHarga.getText());
                stmt.executeUpdate();

                peminjam();
                hapusTransaksi();
                inputPlat();
                TampilData();
//                tabelDataPengembalian();

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (kondisi.getText().equals("Sedang Dibawa")) {
            JOptionPane.showMessageDialog(null, "Pilih Mobil Yang Lain !", "Peringatan", JOptionPane.ERROR_MESSAGE);
        } else {
            simpan();
            Connection conn = Koneksi.getConnection();
            try {
                java.sql.Statement stmt = conn.createStatement();
                SQL = "update mobil set kondisi= 'Sedang Dibawa' WHERE nopol='" + inputPlat.getSelectedItem().toString() + "'";
                stmt.executeUpdate(SQL);

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pilihNopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihNopolActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            String st = (String) pilihNopol.getSelectedItem();
            SQL = "SELECT * FROM mobil WHERE `mobil`.`nopol` = '"+st+"'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {

                this.namaPeminjam.setText(res.getString("nama"));
                this.tglPengembalian.setText(res.getString("tgl_pengembalian"));
                this.tglSewa.setText(res.getString("tgl_pinjaman"));
                this.lamaDipinjam.setText(res.getString("lama"));
                this.hargaSewaHari.setText(res.getString("harga"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_pilihNopolActionPerformed

    private void tblMobilDipinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMobilDipinjamMouseClicked
        // TODO add your handling code here:
        namaPeminjam.setText(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 0)));
        pilihNopol.setSelectedItem(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 1)));
        hargaSewaHari.setText(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 2)));
        tglSewa.setText(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 3)));
        tglPengembalian.setText(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 4)));
        lamaDipinjam.setText(String.valueOf(tblMobilDipinjam.getValueAt(tblMobilDipinjam.getSelectedRow(), 5)));
    }//GEN-LAST:event_tblMobilDipinjamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //        try {
            //            Connection conn = Koneksi.getConnection();
            //            String sql = "SELECT * FROM user WHERE username='" + txtusername.getText() + "' AND password='" + txtpassword.getText() + "'";
            //            System.out.println(sql);
            //            Statement stmt = conn.createStatement();
            //            ResultSet res = stmt.executeQuery(sql);
            //            if (res.next()) {
                //                if (txtusername.getText().equals(res.getString("username")) && txtpassword.getText().equals(res.getString("password"))) {
                    //
                    //                    homeAdmin h = new homeAdmin();
                    //                    h.setVisible(true);
                    //                }
                //            } else {
                //                JOptionPane.showMessageDialog(null, "username atau password salah");
                //            }
            //        } catch (SQLException e) {
            //            System.out.println(e.getMessage());
            //        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSewaMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSewaMobilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSewaMobilMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        login h = new login();
        h.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

   
//    private void bersihMobilKembali() {
//        NamaKembali.setText("");
//        NopolKembali.setSelectedItem(0);
//        HargaKembali.setText("");
//        tglPenyewaanKembali.setText("");
//        tglPengembalianKembali.setText("");
//    }
//    
//    private void bersihMobil() {
//        inputMerk.setText("");
//        inputCC.setText("");
//        inputType.setText("");
//        inputTahunProd.setSelectedItem(0);
//        inputNopol.setText("");
//        inputHargaSewa.setText("");
//        inputKondisi.setSelectedItem(0);
//    }
    
    private void tampilCombo() {
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM mobil";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {
                inputPlat.addItem(res.getString("nopol"));

            }
            res.last();
            int jumlahdata = res.getRow();
            res.first();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void tampilCombo2() {
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM mobil";
            java.sql.ResultSet res = stmt.executeQuery(SQL);

            while (res.next()) {
                pilihNopol.addItem(res.getString("nopol"));

            }
            res.last();
            int jumlahdata = res.getRow();
            res.first();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }
    
//    private void tampilCombo3() {
//        Connection conn = Koneksi.getConnection();
//        try {
//            java.sql.Statement stmt = conn.createStatement();
//            SQL = "SELECT * FROM data_pengembalian";
//            java.sql.ResultSet res = stmt.executeQuery(SQL);
//
//            while (res.next()) {
//               // NopolKembali.addItem(res.getString("nopol"));
//
//            }
//            res.last();
//            int jumlahdata = res.getRow();
//            res.first();
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//
//    }
    
    public void hitungselisih() {
        try {
            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            String strDate1 = df.format(tglPinjam.getDate());
            String strDate2 = df.format(tglKembali.getDate());
            Date Tanggal1 = df.parse(strDate1);
            Date Tanggal2 = df.parse(strDate2);
            long Hari1 = Tanggal1.getTime();
            long Hari2 = Tanggal2.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            if (Lama < 1) {
                JOptionPane.showMessageDialog(null, "Tanggal Salah !", "Peringatan", JOptionPane.ERROR_MESSAGE);
            } else {
                String Hasil = (Long.toString(Lama));
                lamaSewa.setText(Hasil);
            }

            int harga_sewa = Integer.parseInt(hargaSewa.getText()); // lbl_harga di pars ke integer
            int lama_sewa = Integer.parseInt(lamaSewa.getText());   // txt_lama di pars ke integer
            int Total = harga_sewa * lama_sewa;                     // mencari total Harga
            String a = Integer.toString(Total);
            totalHarga.setText(a);

        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, "Masukan Tanggal Peminjaman dan Tanggal Pengembalian");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELJALAN;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel berjalan;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel cc;
    private javax.swing.JLabel hargaSewa;
    private javax.swing.JLabel hargaSewaHari;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JComboBox<String> inputJaminan;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomor;
    private javax.swing.JComboBox<String> inputPlat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jaminan;
    private javax.swing.JLabel kondisi;
    private javax.swing.JLabel lamaDipinjam;
    private javax.swing.JTextField lamaSewa;
    private javax.swing.JLabel merkMobil;
    private javax.swing.JLabel namaPeminjam;
    private javax.swing.JLabel namapeminjam;
    private javax.swing.JLabel nomortlp;
    private javax.swing.JPanel panelHomeAdmin;
    private javax.swing.JComboBox<String> pilihNopol;
    private javax.swing.JLabel tahunMobil;
    private javax.swing.JTable tblMobilDipinjam;
    private javax.swing.JTable tblSewaMobil;
    private com.toedter.calendar.JDateChooser tglKembali;
    private javax.swing.JLabel tglPengembalian;
    private com.toedter.calendar.JDateChooser tglPinjam;
    private javax.swing.JLabel tglSewa;
    private javax.swing.JLabel totalHarga;
    private javax.swing.JLabel typeMobil;
    // End of variables declaration//GEN-END:variables
}
